// LOG ACTIONS
export const SET_LOG = 'SET_LOG'
export const SET_MORE_LOG = 'SET_MORE_LOG'
export const SET_LOG_ENTRY_ID = 'SET_LOG_ENTRY_ID'
export const SET_LOG_ENTRY_NAME = 'SET_LOG_ENTRY_NAME'
export const SET_LOG_ENTRY_TIDE = 'SET_LOG_ENTRY_TIDE'
export const SET_LOG_ENTRY_WATER_TEMP = 'SET_LOG_ENTRY_WATER_TEMP'
export const SET_LOG_ENTRY_START_DATE = 'SET_LOG_ENTRY_START_DATE'
export const SET_LOG_ENTRY_END_DATE = 'SET_LOG_ENTRY_END_DATE'
export const SET_LOG_ENTRY_POSITION = 'SET_LOG_ENTRY_POSITION'
export const SET_LOG_ENTRY_WIND = 'SET_LOG_ENTRY_WIND'
export const SET_LOG_ENTRY_WEATHER = 'SET_LOG_ENTRY_WEATHER'
export const SET_LOG_ENTRY_NOTES = 'SET_LOG_ENTRY_NOTES'
export const SET_LOG_ENTRY_FISHES = 'SET_LOG_ENTRY_FISHES'
export const SET_LOG_ENTRY_RATING = 'SET_LOG_ENTRY_RATING'
export const RESET_LOG_ENTRY = 'RESET_LOG_ENTRY'
export const SET_LOG_ENTRY_FOR_EDIT = 'SET_LOG_ENTRY_FOR_EDIT'
export const SET_LOG_ENTRY_AUTH_PROFILE_ID = 'SET_LOG_ENTRY_AUTH_PROFILE_ID'

// WIZARD ACTIONS
export const ADD = 'ADD'
export const PREVIOUS_NEW_LOG_ENTRY_PANEL = 'PREVIOUS'
export const NEXT_NEW_LOG_ENTRY_PANEL = 'NEXT'
export const RESET_NEW_LOG_ENTRY_PANEL = 'RESET'

// POUCH/COUCH SYNC ACTIONS
export const SYNC_CHANGE = 'SYNC_CHANGE'
export const SYNC_PAUSED = 'SYNC_PAUSED'
export const SYNC_ACTIVE = 'SYNC_ACTIVE'
export const SYNC_DENIED = 'SYNC_DENIED'
export const SYNC_ERROR = 'SYNC_ERROR'
export const LOADING_DATA = 'LOADING_DATA'

// AUTH ACTIONS
export const SET_SESSION = 'SET_SESSION'
export const SET_USER_X = 'SET_USER_'
export const SET_USER = 'SET_USER'
export const CLEAR_PROFILE = 'CLEAR_USER'
