//GET http://api.wunderground.com/api/c88ea0ce3f39121f/conditions/q/SC/Mt_Pleasant.json

const weatherConditions = {
	response: {
		version: '0.1',
		termsofService: 'http://www.wunderground.com/weather/api/d/terms.html',
		features: {
			conditions: 1
		}
	},
	current_observation: {
		image: {
			url: 'http://icons.wxug.com/graphics/wu2/logo_130x80.png',
			title: 'Weather Underground',
			link: 'http://www.wunderground.com'
		},
		display_location: {
			full: 'Mount Pleasant, SC',
			city: 'Mount Pleasant',
			state: 'SC',
			state_name: 'South Carolina',
			country: 'US',
			country_iso3166: 'US',
			zip: '29464',
			magic: '1',
			wmo: '99999',
			latitude: '32.83000183',
			longitude: '-79.83999634',
			elevation: '0.9'
		},
		observation_location: {
			full: 'Snee Farm, Mt. Pleasant, South Carolina',
			city: 'Snee Farm, Mt. Pleasant',
			state: 'South Carolina',
			country: 'US',
			country_iso3166: 'US',
			latitude: '32.835999',
			longitude: '-79.837601',
			elevation: '22 ft'
		},
		estimated: {},
		station_id: 'KSCMTPLE3',
		observation_time: 'Last Updated on May 3, 9:45 AM EDT',
		observation_time_rfc822: 'Wed, 03 May 2017 09:45:13 -0400',
		observation_epoch: '1493819113',
		local_time_rfc822: 'Wed, 03 May 2017 09:49:18 -0400',
		local_epoch: '1493819358',
		local_tz_short: 'EDT',
		local_tz_long: 'America/New_York',
		local_tz_offset: '-0400',
		weather: 'Clear',
		temperature_string: '72.5 F (22.5 C)',
		temp_f: 72.5,
		temp_c: 22.5,
		relative_humidity: '60%',
		wind_string: 'Calm',
		wind_dir: 'North',
		wind_degrees: 355,
		wind_mph: 0.0,
		wind_gust_mph: 0,
		wind_kph: 0,
		wind_gust_kph: 0,
		pressure_mb: '1018',
		pressure_in: '30.06',
		pressure_trend: '+',
		dewpoint_string: '58 F (14 C)',
		dewpoint_f: 58,
		dewpoint_c: 14,
		heat_index_string: 'NA',
		heat_index_f: 'NA',
		heat_index_c: 'NA',
		windchill_string: 'NA',
		windchill_f: 'NA',
		windchill_c: 'NA',
		feelslike_string: '72.5 F (22.5 C)',
		feelslike_f: '72.5',
		feelslike_c: '22.5',
		visibility_mi: '10.0',
		visibility_km: '16.1',
		solarradiation: '--',
		UV: '3',
		precip_1hr_string: '0.00 in ( 0 mm)',
		precip_1hr_in: '0.00',
		precip_1hr_metric: ' 0',
		precip_today_string: '0.00 in (0 mm)',
		precip_today_in: '0.00',
		precip_today_metric: '0',
		icon: 'clear',
		icon_url: 'http://icons.wxug.com/i/c/k/clear.gif',
		forecast_url: 'http://www.wunderground.com/US/SC/Mount_Pleasant.html',
		history_url: 'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KSCMTPLE3',
		ob_url: 'http://www.wunderground.com/cgi-bin/findweather/getForecast?query=32.835999,-79.837601',
		nowcast: ''
	}
}
